apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: echo-server
  app.kubernetes.io/part-of: echo-fleet
resources:
  - deployment.yaml
  - service.yaml